### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'record' referenced before the assignment

### ISSUE THREAD

**Issue by erikpohl53** [NREL/shift#6]
### Contact details

erik.pohl@nrel.gov

### Tell us what you have found

<img width="653" alt="Bug" src="https://user-images.githubusercontent.com/106978961/179276927-05f7ef1c-8383-43d6-a82f-a220482c4d55.PNG">

Error when building secondary network

### OS Platform

Windows 10 and above

**Comment by KapilDuwadi** [comment]
Hi @erikpohl53  can you update the bug title with the actual error message ? In this case title should be "UnboundLocalError: local variable 'record' referenced before the assignment"

**Comment by KapilDuwadi** [comment]
Closing this issue . The reason for this error is because large ampacity conductor is used and catalog is not found. Updated to raise appropriate exceptions.
